export default {
  ADD_TASK: 'ADD_TASK',
  EDIT_TASK: 'EDIT_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  COMPLETE_TASK: 'COMPLETE_TASK',
  SET_KEYWORD: 'SET_KEYWORD',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',
};